### ISSUE TITLE
USRCAT scores

### ISSUE THREAD

**Issue by miha-skalic** [stevenshave/USRCAT#1]
hi @stevenshave ,

I have tried your software and have a question regarding the scores the program produces. When I run in on my data I get values from ~50-2000, which is a substantially different from values on a online platform (http://usr.marseille.inserm.fr/), which range [0.-1.].

Can you provide some insight why this is the case? Thanks!

best, 
Miha

**Comment by miha-skalic** [comment]
to elaborate on my question:
I was referring to "USRCATScore" written in output sdf (which I assume is the main output).

**Comment by stevenshave** [comment]
Hi Miha,
Sorry for the delay in replying.  The issue is my non-standard implementation of the scoring function which operates on the descriptors.  On http://usr.marseille.inserm.fr/, 0=theoretical maximum dissimilarity, and 1=identical.  Using my score, 0 denotes identical molecules and increasing values denote greater dissimilarity.  I will update the software to make this clear.  Thanks for the message.
Best.
Steven

**Comment by miha-skalic** [comment]
Thanks for your reply Steven,
by looking at your implementation https://github.com/oddt/oddt of USRCAT here and your source code I figured out as well. Though, there are still some difference in shape descriptors generated by ODDT and the implementation that you have here. Would you know why that is the case?

best, 
Miha

**Comment by stevenshave** [comment]
Hi Miha,

After looking into the problem I see that ODDT uses rdkit to read molecules.  I compared my implementation with RDKit and discovered two things.  
1) I was using a slightly different method to calculate variance and skew.  This has now been updated in #48dacfea and uses the RDKit method.
2) The way aromaticity is perceived in RDKit vs OpenBabel is bringing up inconsistencies.  Reading the aromaticity posts on their development boards is a real rabbit hole. 

Since RDKit included USRCAT, I have just used RDKit to generate all of my descriptors and do not use this code any more.

Best.
Steven
